#!/bin/bash
# postrm script for astroberry-server-wui

# ======================================== USER SETTINGS ===============================================

# Remove astroberry user
# LEAVE IT UNTOUCHED

# Set GUI autologin for astroberry user
if [ -e /etc/lightdm/lightdm.conf ] && [ -n "$(cut -d: -f1 /etc/passwd | grep pi)" ] && [ -n "$(grep '^autologin-user=' /etc/lightdm/lightdm.conf)" ]
then
    sed -i "s/^autologin-user=.*/autologin-user=pi/g" /etc/lightdm/lightdm.conf
fi

# Restore console autologin for pi user
if [ -e /etc/systemd/system/getty@tty1.service.d/autologin.conf ]
then
    sed -i "s/^astroberry$/pi/g" /etc/systemd/system/getty@tty1.service.d/autologin.conf
fi

# Restore defaults for authorization for pi user only
if [ -e /etc/polkit-1/localauthority.conf.d/70-localauthority.conf ]
then
    rm -rf /etc/polkit-1/localauthority.conf.d/70-localauthority.conf
fi

# ========================================= SWAP SETTINGS ==============================================

# disable zram swap
if [ -z "$(systemctl status zramswap.service | grep enabled)" ]
then
    systemctl stop zramswap.service
    systemctl disable zramswap.service
    sed -i "s/^PERCENTAGE/#PERCENTAGE/g" /etc/default/zramswap
fi

# ========================================= BOOT SETTINGS ==============================================

# set display to 1920x1080
# see available modes: https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

if [ -n "$(grep '^hdmi_force_hotplug=1' /boot/config.txt)" ]
then
    sed -i "s/hdmi_force_hotplug=1//g" /boot/config.txt
fi

if [ -n "$(grep '^hdmi_group=2' /boot/config.txt)" ]
then
    sed -i "s/hdmi_group=2//g" /boot/config.txt
fi

if [ -n "$(grep '^hdmi_mode=82' /boot/config.txt)" ]
then
    sed -i "s/hdmi_mode=82//g" /boot/config.txt
fi

# enable I2C
if [ -n "$(grep '^dtparam=i2c_arm=on' /boot/config.txt)" ]
then
    sed -i "s/dtparam=i2c_arm=on//g" /boot/config.txt
fi

# enable SPI
if [ -n "$(grep '^dtparam=spi=on' /boot/config.txt)" ]
then
    sed -i "s/dtparam=spi=on//g" /boot/config.txt
fi

# enable audio
if [ -n "$(grep '^dtparam=audio=on' /boot/config.txt)" ]
then
    sed -i "s/dtparam=audio=on//g" /boot/config.txt
fi

# enable uart
if [ -n "$(grep '^enable_uart=1' /boot/config.txt)" ]
then
    sed -i "s/enable_uart=1//g" /boot/config.txt
fi

# set gpu memory
if [ -n "$(grep '^gpu_mem=128' /boot/config.txt)" ]
then
    sed -i "s/gpu_mem=128//g" /boot/config.txt
fi

# ========================================= TWEAKS ======================================================

# set hostname
if [ -n "$(grep 'astroberry' /etc/hostname)" ]
then
    echo "raspberrypi" > /etc/hostname
fi

if [ -n "$(grep 'astroberry' /etc/hosts)" ]
then
    sed -i "s/astroberry/raspberrypi/g" /etc/hosts
fi

# remove pi password change prompt
touch /run/sshwarn

# configure lxde-astroberry
update-alternatives --remove x-session-manager /usr/bin/startlxde-astroberry

# disactivate custom configuration for samba
pdbedit -x astroberry
systemctl reload smbd.service

# purge all package data
if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db
    db_purge
fi
