#!/bin/bash
# postinst script for astroberry-server-sysmod
# Some tweaks come from AstroPi https://github.com/rlancaste/AstroPi3
# For all of these credits go to Rob Lancaster

# ======================================== USER SETTINGS ===============================================

# Setup astroberry user
if [ -z "$(cut -d: -f1 /etc/passwd | grep astroberry)" ];
then
    useradd -m -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi astroberry

    # Source debconf library.
    . /usr/share/debconf/confmodule
    db_get astroberry-server-sysmod/password
    PASSWORD=$RET
    echo -e "$PASSWORD\n$PASSWORD" | passwd astroberry
    echo -e "$PASSWORD\n$PASSWORD" | smbpasswd -s -a astroberry
fi

# Set GUI autologin for astroberry user
if [ -e /etc/lightdm/lightdm.conf ] && [ -n "$(cut -d: -f1 /etc/passwd | grep astroberry)" ] && [ -n "$(grep '^autologin-user=' /etc/lightdm/lightdm.conf)" ]
then
    sed -i "s/^autologin-user=.*/autologin-user=astroberry/g" /etc/lightdm/lightdm.conf
fi

# Set console autologin for astroberry user
if [ -e /etc/systemd/system/getty@tty1.service.d/autologin.conf ]
then
    sed -i "s/^pi$/astroberry/g" /etc/systemd/system/getty@tty1.service.d/autologin.conf
fi

# Set authorization for all sudo users
if [ ! -e /etc/polkit-1/localauthority.conf.d/70-localauthority.conf ]
then
    echo -e "[Configuration]\nAdminIdentities=unix-group:sudo" > /etc/polkit-1/localauthority.conf.d/70-localauthority.conf
fi

# ========================================= SWAP SETTINGS ==============================================

# setup zram swap
if [ -z "$(systemctl status zramswap.service | grep enabled)" ]
then
    sed -i "s/#PERCENTAGE/PERCENTAGE/g" /etc/default/zramswap
fi

# ========================================= BOOT SETTINGS ==============================================

# set display to 1920x1080
# see available modes: https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

if [ -z "$(grep '^hdmi_force_hotplug=' /boot/config.txt)" ]
then
    echo "hdmi_force_hotplug=1" >> /boot/config.txt
fi

if [ -z "$(grep '^hdmi_group=' /boot/config.txt)" ]
then
    echo "hdmi_group=2" >> /boot/config.txt
fi

if [ -z "$(grep '^hdmi_mode=' /boot/config.txt)" ]
then
    echo "hdmi_mode=82" >> /boot/config.txt
fi

# enable I2C
if [ -z "$(grep '^dtparam=i2c_arm=on' /boot/config.txt)" ]
then
    echo "dtparam=i2c_arm=on" >> /boot/config.txt
fi

# enable SPI
if [ -z "$(grep '^dtparam=spi=on' /boot/config.txt)" ]
then
    echo "dtparam=spi=on" >> /boot/config.txt
fi

# enable audio
if [ -z "$(grep '^dtparam=audio=on' /boot/config.txt)" ]
then
    echo "dtparam=audio=on" >> /boot/config.txt
fi

# enable uart
if [ -z "$(grep '^enable_uart=1' /boot/config.txt)" ]
then
    echo "enable_uart=1" >> /boot/config.txt
fi

# set gpu memory
if [ -z "$(grep '^gpu_mem=' /boot/config.txt)" ]
then
    echo "gpu_mem=128" >> /boot/config.txt
fi

# ========================================= TWEAKS ======================================================

# set hostname
if [ -n "$(grep 'raspberrypi' /etc/hostname)" ]
then
    echo "astroberry" > /etc/hostname
fi

if [ -n "$(grep 'raspberrypi' /etc/hosts)" ]
then
    sed -i "s/raspberrypi/astroberry/g" /etc/hosts
fi

# remove pi password change prompt
rm -rf /run/sshwarn

# configure lxde-astroberry
update-alternatives --install /usr/bin/x-session-manager x-session-manager /usr/bin/startlxde-astroberry 95

# activate custom configuration for samba
if [ -n "$(cut -d: -f1 /etc/passwd | grep astroberry)" ] && [ -z "$(grep '\[astroberry\]' /etc/samba/smb.conf)" ]
then
    cat >> /etc/samba/smb.conf << EOF

[astroberry]
   comment = Astroberry Home
   path = /home/astroberry
   browseable = yes
   writeable = yes
   read only = no
   create mask = 0644
   directory mask = 0755
   valid users = astroberry
EOF

    db_get astroberry-server-sysmod/password
    PASSWORD=$RET
    echo -e "$PASSWORD\n$PASSWORD" | smbpasswd -s -a astroberry
    systemctl reload smbd.service
fi
